### PR TITLE
SF5 Compatibility

### PR DESCRIPTION
**Pull request by magarzon**
Added SF5 compatibility

### CODE REVIEW

**Comment by gorghoa** [comment]
Thanks @magarzon :+1:

@vincentchalamon, builds failed on php5.5 and 5.6. I think we could allow them to fail, what do you think (see #39)  ?

@magarzon, have you actually successfully run it with symfony 5 ?

**Comment by gorghoa** [comment]
Builds for #39 are not passing yet, but I am comfortable with your PR being merged now @magarzon.

Can you just allow php 5.5 and 5.6 to fail in `.travis.yml` ?

I’m open to divergent opinions though :-°

**Comment by magarzon** [comment]
> Thanks @magarzon 
> 
> @vincentchalamon, builds failed on php5.5 and 5.6. I think we could allow them to fail, what do you think (see #39) ?
> 
> @magarzon, have you actually successfully run it with symfony 5 ?

Yes, I have tested in SF5 and it works.

**Review by gorghoa — APPROVED** [review]

**Comment by gorghoa** [comment]
thanks @magarzon :+1:, v1.0.7 tagged

**Pull request merged**
