### PR TITLE
Autoload ScenarioStateArgument upon extension initialisation

### LINKED ISSUE #19: Unable to autoload ScenarioStateArgument
The ScenarioStateArgument doesn't seem to be working by default.

It gives a:
```
 [Doctrine\Common\Annotations\AnnotationException]
  [Semantical Error] The annotation "@Gorghoa\ScenarioStateBehatExtension\Annotation\ScenarioStateArgument" in method ForumContext::iVisitTheForumPage() does not exist, or could not be auto-loaded.
```

I would expect to have it autoloaded automatically [instead of adding code specifically for autoloading it](https://github.com/gorghoa/ScenarioStateBehatExtension/blob/ecc1696d43406f99b346e3d5ef9aea7ae89edca9/testapp/features/bootstrap/FeatureContext.php#L25-L28).

Here's my context:
```
<?php

use Gorghoa\ScenarioStateBehatExtension\Context\ScenarioStateAwareContext;
use Gorghoa\ScenarioStateBehatExtension\Context\ScenarioStateAwareTrait;
use Page\ForumPage;
use Gorghoa\ScenarioStateBehatExtension\Annotation\ScenarioStateArgument;
use SensioLabs\Behat\PageObjectExtension\Context\PageObjectContext;

/**
 * Class ForumContext
 */
class ForumContext extends PageObjectContext implements ScenarioStateAwareContext
{
    use ScenarioStateAwareTrait;

    /**
     * @When I visit the :forumName forum page
     *
     * @ScenarioStateArgument(name="forumName", argument="storedForumName")
     *
     * @param string $forumName
     * @param string $storedForumName
     */
    public function iVisitTheForumPage($forumName, $storedForumName)
    {
        $this->getPage(ForumPage::class)->open(['forum' => $storedForumName]);
    }
}
```

### PR DESCRIPTION
**Pull request by walterdolce**
This should fix #19

### CODE REVIEW

**Comment by gorghoa** [comment]
Hi @walterdolce, thanks for your feedback and PR, we really appreciate your help !

Even if all tests are green, we’ll need to try on a real symfony project to validate it does not break a thing.

**Comment by walterdolce** [comment]
@gorghoa you're welcome!

> Even if all tests are green, we’ll need to try on a real symfony project to validate it does not break a thing.

Why would it? It's just a behat extension. 
But sure, please run your checks..

**Comment by vincentchalamon** [comment]
@walterdolce I actually run this extension on multiple Symfony-standard-edition projects without any problem, so it means it's automatically registered by the project. I just want to be sure it won't break other projects by double-loading this annotation 😉

**Comment by vincentchalamon** [comment]
@walterdolce I guess your project is not a Symfony standard edition? How do you load other annotations in your project?

**Comment by walterdolce** [comment]
>  I guess your project is not a Symfony standard edition? How do you load other annotations in your project?

My project is not a Symfony project at all :-)
No other annotations loaded. Just the one provided by the extension.

**Comment by vincentchalamon** [comment]
@walterdolce OK thanks, we're checking on Symfony projects and be back in a few minutes :-)

**Review by vincentchalamon — APPROVED** [review]

**Comment by vincentchalamon** [comment]
Thanks @walterdolce

**Pull request merged**
